[build]
  # Build-Kommando (nicht notwendig f端r reine HTML/CSS/JS, aber wir erstellen ein build.js)
  command = "node build.js"
  # Publish-Verzeichnis
  publish = "dist"

# Redirect-Regeln f端r SPA
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

# Environment Variables werden 端ber Netlify Dashboard gesetzt
# Siehe NETLIFY-SETUP.md f端r Anleitung